//! RISC0 zkVM Prover for Raiko V2
//!
//! This module provides the RISC0 prover implementation for generating
//! zero-knowledge proofs of Taiko block execution.

use alloy_primitives::B256;
use raiko2_primitives::{
    AggregationGuestInput, GuestInput, Proof, ProverConfig, ProverError, ProverResult,
    ShastaZkAggregationGuestInput,
};
use raiko2_protocol::ProofCarryData;
use risc0_zkvm::{ExecutorEnv, ProverOpts, Receipt, compute_image_id, default_prover};
use serde::{Deserialize, Serialize};
use tracing::info;

// Generated methods from guest build
pub mod methods;

/// RISC0 prover configuration parameters.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Risc0Config {
    /// Whether to use Bonsai proving service.
    pub bonsai: bool,
    /// Whether to generate SNARK proof.
    pub snark: bool,
    /// Whether to enable profiling.
    pub profile: bool,
    /// Execution power of 2 (for cycle limit).
    pub execution_po2: u32,
    /// Whether to verify the proof after generation.
    #[serde(default = "default_true")]
    pub verify: bool,
}

const fn default_true() -> bool {
    true
}

impl Default for Risc0Config {
    fn default() -> Self {
        Self {
            bonsai: true,
            snark: true,
            profile: false,
            execution_po2: 20,
            verify: true,
        }
    }
}

/// RISC0 proof response.
#[derive(Clone, Serialize, Deserialize)]
pub struct Risc0Response {
    /// Hex-encoded proof (journal bytes)
    pub proof: String,
    /// JSON-serialized receipt
    pub receipt: String,
    /// Image ID of the guest program
    pub image_id: String,
    /// Public input hash
    pub input: B256,
}

impl From<Risc0Response> for Proof {
    fn from(value: Risc0Response) -> Self {
        Self {
            proof: Some(value.proof),
            quote: Some(value.receipt),
            input: Some(value.input),
            uuid: Some(value.image_id),
            kzg_proof: None,
            extra_data: None,
        }
    }
}

/// RISC0 Prover for Shasta batch proofs.
pub struct Risc0Prover {
    config: Risc0Config,
}

impl Risc0Prover {
    /// Create a new RISC0 prover with the given configuration.
    pub const fn new(config: Risc0Config) -> Self {
        Self { config }
    }
}

#[async_trait::async_trait]
impl crate::Prover for Risc0Prover {
    async fn prove(&self, input: GuestInput, config: &ProverConfig) -> ProverResult<Proof> {
        info!("Starting RISC0 batch proof generation...");

        // Extract ProofCarryData from config if available
        let proof_carry_data: ProofCarryData = serde_json::from_value(
            config
                .get("proof_carry_data")
                .cloned()
                .unwrap_or(serde_json::Value::Null),
        )
        .unwrap_or_default();

        // Build the executor environment with both inputs
        // The guest reads:
        // 1. GuestInput via env::read()
        // 2. ProofCarryData via env::read()
        let env = ExecutorEnv::builder()
            .write(&input)
            .map_err(|e| ProverError::GuestError(format!("Failed to write input: {}", e)))?
            .write(&proof_carry_data)
            .map_err(|e| {
                ProverError::GuestError(format!("Failed to write proof_carry_data: {}", e))
            })?
            .build()
            .map_err(|e| ProverError::GuestError(format!("Failed to build env: {}", e)))?;

        let opts = if self.config.snark {
            ProverOpts::groth16()
        } else {
            ProverOpts::default()
        };

        // Use proposal ELF (will be generated by build-guest.sh)
        let elf = methods::RISC0_BATCH_ELF;
        let image_id = compute_image_id(elf)
            .map_err(|e| ProverError::GuestError(format!("Failed to compute image id: {}", e)))?;

        info!("Starting RISC0 batch proof generation...");
        let prove_info = default_prover()
            .prove_with_opts(env, elf, &opts)
            .map_err(|e| {
                tracing::error!("Failed to generate RISC0 batch proof: {:?}", e);
                ProverError::GuestError(format!("RISC0 batch proof generation failed: {}", e))
            })?;

        let receipt = prove_info.receipt;

        info!("RISC0 batch proof generated successfully");

        // Verify proof if configured
        if self.config.verify {
            receipt.verify(image_id).map_err(|e| {
                tracing::error!("Failed to verify RISC0 batch proof: {:?}", e);
                ProverError::GuestError(format!("RISC0 batch proof verification failed: {}", e))
            })?;
            info!("RISC0 batch proof verified successfully");
        }

        // Extract public values (instance_hash + subproof_input_hash = 64 bytes)
        let journal_bytes = &receipt.journal.bytes;
        let input_hash = if journal_bytes.len() >= 32 {
            B256::from_slice(&journal_bytes[..32])
        } else {
            B256::default()
        };

        info!(
            "Generated batch receipt journal: {:?}",
            alloy_primitives::hex::encode_prefixed(journal_bytes.clone())
        );

        // Serialize receipt for storage
        let receipt_json = serde_json::to_string(&receipt).unwrap_or_default();

        Ok(Risc0Response {
            proof: alloy_primitives::hex::encode_prefixed(journal_bytes),
            receipt: receipt_json,
            image_id: alloy_primitives::hex::encode_prefixed(image_id.as_bytes()),
            input: input_hash,
        }
        .into())
    }

    async fn aggregate(
        &self,
        input: AggregationGuestInput,
        config: &ProverConfig,
    ) -> ProverResult<Proof> {
        info!(
            "Starting RISC0 aggregation proof generation with {} proofs...",
            input.proofs.len()
        );

        // Extract ShastaZkAggregationGuestInput from config
        let aggregation_input: ShastaZkAggregationGuestInput = serde_json::from_value(
            config
                .get("shasta_zk_aggregation_input")
                .cloned()
                .ok_or_else(|| {
                    ProverError::GuestError(
                        "Missing 'shasta_zk_aggregation_input' in config".to_string(),
                    )
                })?,
        )
        .map_err(|e| {
            ProverError::GuestError(format!("Failed to parse aggregation input: {}", e))
        })?;

        // Validate input length matches
        if aggregation_input.block_inputs.len() != aggregation_input.proof_carry_data_vec.len() {
            return Err(ProverError::GuestError(
                "Mismatched block_inputs and proof_carry_data_vec lengths".to_string(),
            ));
        }

        // Get batch image ID for proof verification
        let batch_elf = methods::RISC0_BATCH_ELF;
        let _batch_image_id = compute_image_id(batch_elf)
            .map_err(|e| ProverError::GuestError(format!("Failed to compute image id: {}", e)))?;

        // Build executor environment with assumptions (proofs to verify)
        let mut env_builder = ExecutorEnv::builder();

        // Write the aggregation input
        env_builder.write(&aggregation_input).map_err(|e| {
            ProverError::GuestError(format!("Failed to write aggregation input: {}", e))
        })?;

        // Add each proof as an assumption for verification
        for proof in &input.proofs {
            // Extract the receipt from the Proof struct
            // The receipt is stored as JSON in the 'quote' field
            if let Some(receipt_json) = &proof.quote {
                let receipt: Receipt = serde_json::from_str(receipt_json).map_err(|e| {
                    ProverError::GuestError(format!("Failed to parse RISC0 receipt: {}", e))
                })?;

                // Add the receipt as an assumption
                env_builder.add_assumption(receipt);
            }
        }

        let env = env_builder
            .build()
            .map_err(|e| ProverError::GuestError(format!("Failed to build env: {}", e)))?;

        let opts = if self.config.snark {
            ProverOpts::groth16()
        } else {
            ProverOpts::default()
        };

        // Use Shasta aggregation ELF
        let elf = methods::RISC0_SHASTA_AGGREGATION_ELF;
        let image_id = compute_image_id(elf)
            .map_err(|e| ProverError::GuestError(format!("Failed to compute image id: {}", e)))?;

        // Generate aggregation proof
        let prove_info = default_prover()
            .prove_with_opts(env, elf, &opts)
            .map_err(|e| {
                tracing::error!("Failed to generate RISC0 aggregation proof: {:?}", e);
                ProverError::GuestError(format!("RISC0 aggregation proof generation failed: {}", e))
            })?;

        let receipt = prove_info.receipt;

        info!("RISC0 aggregation proof generated successfully");

        // Verify proof if configured
        if self.config.verify {
            receipt.verify(image_id).map_err(|e| {
                tracing::error!("Failed to verify RISC0 aggregation proof: {:?}", e);
                ProverError::GuestError(format!(
                    "RISC0 aggregation proof verification failed: {}",
                    e
                ))
            })?;
            info!("RISC0 aggregation proof verified successfully");
        }

        // Extract public values (agg_public_input_hash = 32 bytes)
        let journal_bytes = &receipt.journal.bytes;
        let agg_input_hash = if journal_bytes.len() >= 32 {
            B256::from_slice(&journal_bytes[..32])
        } else {
            B256::default()
        };

        // Serialize receipt for storage
        let receipt_json = serde_json::to_string(&receipt).unwrap_or_default();

        Ok(Risc0Response {
            proof: alloy_primitives::hex::encode_prefixed(journal_bytes),
            receipt: receipt_json,
            image_id: alloy_primitives::hex::encode_prefixed(image_id.as_bytes()),
            input: agg_input_hash,
        }
        .into())
    }
}
