[package]
name = "raiko2-stateless"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
alethia-reth-block-lite.workspace = true
alethia-reth-chainspec-lite.workspace = true

# Alloy
alloy-rlp.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true

# Reth
reth-stateless.workspace = true
reth-ethereum-primitives.workspace = true
reth-primitives-traits.workspace = true
