[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
alloy = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
raiko2-guests = { workspace = true }
raiko2-pipeline = { workspace = true }
raiko2-primitives = { workspace = true }
raiko2-primitives-shasta = { workspace = true }
raiko2-provider = { workspace = true }
raiko2-protocol-shasta = { workspace = true }
reth-ethereum-primitives = { workspace = true }
risc0-zkvm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sp1-sdk = { workspace = true }
tokio = { workspace = true }
xtask-build-guest = { path = "./build-guest" }
