//! SP1 zkVM Prover for Raiko V2
//!
//! This module provides the SP1 prover implementation for generating
//! zero-knowledge proofs of Taiko block execution.

mod types;

pub use types::{ProverMode, RecursionMode, Sp1Config, Sp1Response};

use alloy_primitives::{B256, Bytes};
use raiko2_pipeline::{ProofStage, ProverBackend};
use raiko2_primitives::{AggregationGuestInput, Proof, ProverConfig, RaikoError, RaikoResult};
use raiko2_primitives_shasta::GuestInput;
use sp1_sdk::{HashableKey, ProverClient, SP1ProofMode, SP1ProofWithPublicValues, SP1Stdin};
use tracing::info;

use crate::{GuestInputCodec, parse_shasta_aggregation_input, validate_shasta_aggregation_lengths};

/// SP1 Prover for Shasta proposal proofs.
pub struct Sp1Prover {
    config: Sp1Config,
}

impl Sp1Prover {
    /// Create a new SP1 prover with the given configuration.
    #[must_use]
    pub const fn new(config: Sp1Config) -> Self {
        Self { config }
    }
}

impl GuestInputCodec<GuestInput> for Sp1Prover {
    fn encode(&self, input: &GuestInput, _config: &ProverConfig) -> RaikoResult<Bytes> {
        let bytes = bincode::serialize(input)
            .map_err(|e| RaikoError::Guest(format!("Failed to serialize input: {e}")))?;
        Ok(Bytes::from(bytes))
    }
}

#[async_trait::async_trait]
impl<B> crate::Prover<B> for Sp1Prover
where
    B: ProverBackend,
{
    type GuestInput = GuestInput;

    fn encode(&self, input: &Self::GuestInput, config: &ProverConfig) -> RaikoResult<Bytes> {
        GuestInputCodec::encode(self, input, config)
    }

    async fn prove_encoded(
        &self,
        input: Bytes,
        _config: &ProverConfig,
        backend: &B,
    ) -> RaikoResult<Proof> {
        info!("Starting SP1 proposal proof generation...");

        // Prepare stdin for SP1 guest program
        // The guest reads a single GuestInput via typed IO.
        let mut stdin = SP1Stdin::new();
        let guest_input: GuestInput = bincode::deserialize(input.as_ref())
            .map_err(|e| RaikoError::Guest(format!("Failed to deserialize input: {e}")))?;
        stdin.write(&guest_input);

        // Create prover client
        let client = ProverClient::from_env();

        // Use proposal ELF (will be generated by build-guest.sh)
        let elf = backend.elf(ProofStage::Proposal)?;

        // Setup proving key and verifying key
        let (pk, vk) = client.setup(elf);

        // Get proof mode
        let proof_mode: SP1ProofMode = self.config.recursion.clone().into();

        // Generate proof
        let proof = client
            .prove(&pk, &stdin)
            .mode(proof_mode)
            .run()
            .map_err(|e| {
                tracing::error!("Failed to generate SP1 proposal proof: {:?}", e);
                RaikoError::Guest(format!("SP1 proposal proof generation failed: {e}"))
            })?;

        info!("SP1 proposal proof generated successfully");

        // Verify proof if configured
        if self.config.verify {
            client.verify(&proof, &vk).map_err(|e| {
                tracing::error!("Failed to verify SP1 proposal proof: {:?}", e);
                RaikoError::Guest(format!("SP1 proposal proof verification failed: {e}"))
            })?;
            info!("SP1 proposal proof verified successfully");
        }

        // Extract public values (instance_hash + subproof_input_hash = 64 bytes)
        let public_values = proof.public_values.as_slice();
        let input_hash = if public_values.len() >= 32 {
            B256::from_slice(&public_values[..32])
        } else {
            B256::default()
        };

        // Encode proof
        let proof_bytes = bincode::serialize(&proof)
            .map_err(|e| RaikoError::Guest(format!("Failed to serialize proof: {e}")))?;

        Ok(Sp1Response {
            proof: Some(alloy_primitives::hex::encode_prefixed(&proof_bytes)),
            vkey_hash: Some(vk.bytes32()),
            input: input_hash,
            sp1_proof: Some(proof),
            vkey: Some(vk),
        }
        .into())
    }

    async fn aggregate(
        &self,
        input: AggregationGuestInput,
        config: &ProverConfig,
        backend: &B,
    ) -> RaikoResult<Proof> {
        info!(
            "Starting SP1 aggregation proof generation with {} proofs...",
            input.proofs.len()
        );

        // Extract ShastaZkAggregationGuestInput from config
        // The caller should provide this in config["shasta_zk_aggregation_input"]
        let aggregation_input = parse_shasta_aggregation_input(config)?;
        validate_shasta_aggregation_lengths(&aggregation_input)?;

        // Prepare stdin for SP1 aggregation guest program
        // The guest reads ShastaZkAggregationGuestInput via sp1_zkvm::io::read()
        let mut stdin = SP1Stdin::new();
        stdin.write(&aggregation_input);

        // Get the proposal prover's verifying key for proof verification.
        // The proposal proofs were generated with the proposal ELF.
        let proposal_elf = backend.elf(ProofStage::Proposal)?;
        let client = ProverClient::from_env();
        let (_, proposal_vk) = client.setup(proposal_elf);

        // Add SP1 proofs for verification within the guest
        // Each proof from input.proofs should be an SP1 proof that can be verified
        for proof in &input.proofs {
            // Extract the SP1ProofWithPublicValues from the Proof struct
            // The proof is stored as hex-encoded bincode in the 'proof' field
            if let Some(proof_hex) = &proof.proof {
                let proof_bytes = alloy_primitives::hex::decode(proof_hex)
                    .map_err(|e| RaikoError::Guest(format!("Failed to decode proof hex: {e}")))?;

                let sp1_proof_with_pv: SP1ProofWithPublicValues =
                    bincode::deserialize(&proof_bytes).map_err(|e| {
                        RaikoError::Guest(format!(
                            "Failed to deserialize SP1ProofWithPublicValues: {e}"
                        ))
                    })?;

                // Extract the SP1ReduceProof from the Compressed variant
                match sp1_proof_with_pv.proof {
                    sp1_sdk::SP1Proof::Compressed(reduce_proof) => {
                        stdin.write_proof(*reduce_proof, proposal_vk.vk.clone());
                    }
                    _ => {
                        return Err(RaikoError::Guest(
                            "Aggregation requires Compressed proofs".to_string(),
                        ));
                    }
                }
            }
        }

        // Use Shasta aggregation ELF
        let elf = backend.elf(ProofStage::Aggregation)?;

        // Setup proving key and verifying key for aggregation
        let (pk, vk) = client.setup(elf);

        // Get proof mode
        let proof_mode: SP1ProofMode = self.config.recursion.clone().into();

        // Generate aggregation proof
        let proof = client
            .prove(&pk, &stdin)
            .mode(proof_mode)
            .run()
            .map_err(|e| {
                tracing::error!("Failed to generate SP1 aggregation proof: {:?}", e);
                RaikoError::Guest(format!("SP1 aggregation proof generation failed: {e}"))
            })?;

        info!("SP1 aggregation proof generated successfully");

        // Verify proof if configured
        if self.config.verify {
            client.verify(&proof, &vk).map_err(|e| {
                tracing::error!("Failed to verify SP1 aggregation proof: {:?}", e);
                RaikoError::Guest(format!("SP1 aggregation proof verification failed: {e}"))
            })?;
            info!("SP1 aggregation proof verified successfully");
        }

        // Extract public values (agg_public_input_hash = 32 bytes)
        let public_values = proof.public_values.as_slice();
        let agg_input_hash = if public_values.len() >= 32 {
            B256::from_slice(&public_values[..32])
        } else {
            B256::default()
        };

        // Encode proof
        let proof_bytes = bincode::serialize(&proof)
            .map_err(|e| RaikoError::Guest(format!("Failed to serialize proof: {e}")))?;

        Ok(Sp1Response {
            proof: Some(alloy_primitives::hex::encode_prefixed(&proof_bytes)),
            vkey_hash: Some(vk.bytes32()),
            input: agg_input_hash,
            sp1_proof: Some(proof),
            vkey: Some(vk),
        }
        .into())
    }
}
