//! SP1 zkVM Prover for Raiko V2
//!
//! This module provides the SP1 prover implementation for generating
//! zero-knowledge proofs of Taiko block execution.

mod types;

pub use types::{
    ExecutionMode, ProverMode, RecursionMode, Sp1Config, Sp1ConfigOverrides, Sp1ExecutionMetadata,
    Sp1Response,
};

use alloy_primitives::Bytes;
use raiko2_pipeline::{ProofStage, ProverBackend};
use raiko2_primitives::{AggregationGuestInput, Proof, ProverConfig, RaikoError, RaikoResult};
use raiko2_primitives_shasta::GuestInput;
use sp1_sdk::{
    Elf, HashableKey, ProveRequest as _, Prover as _, ProverClient, ProvingKey as _, SP1Proof,
    SP1ProofMode, SP1ProofWithPublicValues, SP1Stdin,
};
use tracing::info;

use crate::{
    GuestInputCodec, parse_shasta_aggregation_input, parse_shasta_aggregation_input_hash,
    parse_shasta_proposal_input_hash, validate_shasta_aggregation_lengths, with_shasta_extra_data,
};

/// SP1 Prover for Shasta proposal proofs.
pub struct Sp1Prover {
    config: Sp1Config,
}

impl Sp1Prover {
    /// Create a new SP1 prover with the given configuration.
    #[must_use]
    pub const fn new(config: Sp1Config) -> Self {
        Self { config }
    }

    fn resolve_config(&self, config: &ProverConfig) -> RaikoResult<Sp1Config> {
        let overrides = config
            .get("sp1")
            .cloned()
            .map(serde_json::from_value::<Sp1ConfigOverrides>)
            .transpose()
            .map_err(|e| {
                RaikoError::InvalidRequestConfig(format!("Failed to parse 'sp1' prover args: {e}"))
            })?
            .unwrap_or_default();
        Ok(self.config.merged_with(&overrides))
    }
}

impl GuestInputCodec<GuestInput> for Sp1Prover {
    fn encode(&self, input: &GuestInput, _config: &ProverConfig) -> RaikoResult<Bytes> {
        let bytes = bincode::serialize(input)
            .map_err(|e| RaikoError::Guest(format!("Failed to serialize input: {e}")))?;
        Ok(Bytes::from(bytes))
    }
}

#[async_trait::async_trait]
impl<B> crate::Prover<B> for Sp1Prover
where
    B: ProverBackend,
{
    type GuestInput = GuestInput;

    fn encode(&self, input: &Self::GuestInput, config: &ProverConfig) -> RaikoResult<Bytes> {
        GuestInputCodec::encode(self, input, config)
    }

    fn prepare_config_for_input(
        &self,
        input: &Self::GuestInput,
        config: &mut ProverConfig,
    ) -> RaikoResult<()> {
        if !config.is_object() {
            *config = serde_json::json!({});
        }
        let Some(config) = config.as_object_mut() else {
            return Err(RaikoError::InvalidRequestConfig(
                "prover config must be a JSON object".to_string(),
            ));
        };
        config.insert(
            "shasta_proof_carry_data".to_string(),
            serde_json::to_value(&input.proof_carry_data).map_err(|e| {
                RaikoError::InvalidRequestConfig(format!(
                    "Failed to serialize proof carry data: {e}"
                ))
            })?,
        );
        Ok(())
    }

    async fn prove_encoded(
        &self,
        input: Bytes,
        config: &ProverConfig,
        backend: &B,
    ) -> RaikoResult<Proof> {
        let effective_config = self.resolve_config(config)?;
        info!(mode = %effective_config.mode.as_str(), "Starting SP1 proposal run...");

        // Prepare stdin for SP1 guest program
        // The guest reads a single GuestInput via typed IO.
        let mut stdin = SP1Stdin::new();
        let guest_input: GuestInput = bincode::deserialize(input.as_ref())
            .map_err(|e| RaikoError::Guest(format!("Failed to deserialize input: {e}")))?;
        stdin.write(&guest_input);

        // Use proposal ELF (will be generated by build-guest.sh)
        let elf = Elf::from(backend.elf(ProofStage::Proposal)?);
        match effective_config.mode.clone() {
            ExecutionMode::Execute => {
                if matches!(effective_config.prover, Some(ProverMode::Network)) {
                    return Err(RaikoError::InvalidRequestConfig(
                        "sp1.mode=execute does not support sp1.prover=network".to_string(),
                    ));
                }
                let client = ProverClient::builder().light().build().await;
                let (public_values, execution_report) =
                    client.execute(elf, stdin).await.map_err(|e| {
                        tracing::error!("Failed to execute SP1 proposal: {:?}", e);
                        RaikoError::Guest(format!("SP1 proposal execute failed: {e}"))
                    })?;
                let public_values_raw = public_values.raw();
                let input_hash = parse_shasta_proposal_input_hash(public_values.as_slice());
                let metadata = serde_json::to_value(Sp1ExecutionMetadata::from_execution_report(
                    public_values_raw,
                    &execution_report,
                ))
                .map_err(|e| {
                    RaikoError::Guest(format!("Failed to serialize SP1 execution metadata: {e}"))
                })?;

                Ok(Sp1Response {
                    proof: None,
                    vkey_hash: None,
                    input: input_hash,
                    sp1_proof: None,
                    vkey: None,
                    extra_data: with_shasta_extra_data(
                        &guest_input.proof_carry_data,
                        "sp1",
                        Some(metadata),
                    )?,
                }
                .into())
            }
            ExecutionMode::Prove => {
                let proof_mode: SP1ProofMode = effective_config.recursion.clone().into();
                match effective_config.prover.unwrap_or(ProverMode::Local) {
                    ProverMode::Mock => {
                        let client = ProverClient::builder().mock().build().await;
                        prove_proposal_with_client(
                            &client,
                            elf,
                            stdin,
                            proof_mode,
                            effective_config.verify,
                            &guest_input,
                        )
                        .await
                    }
                    ProverMode::Local => {
                        let client = ProverClient::builder().cpu().build().await;
                        prove_proposal_with_client(
                            &client,
                            elf,
                            stdin,
                            proof_mode,
                            effective_config.verify,
                            &guest_input,
                        )
                        .await
                    }
                    ProverMode::Network => {
                        let client = ProverClient::from_env().await;
                        prove_proposal_with_client(
                            &client,
                            elf,
                            stdin,
                            proof_mode,
                            effective_config.verify,
                            &guest_input,
                        )
                        .await
                    }
                }
            }
        }
    }

    async fn aggregate(
        &self,
        input: AggregationGuestInput,
        config: &ProverConfig,
        backend: &B,
    ) -> RaikoResult<Proof> {
        let effective_config = self.resolve_config(config)?;
        if matches!(effective_config.mode.clone(), ExecutionMode::Execute) {
            return Err(RaikoError::InvalidRequestConfig(
                "sp1.mode=execute is not supported for aggregation".to_string(),
            ));
        }
        info!(
            "Starting SP1 aggregation proof generation with {} proofs...",
            input.proofs.len()
        );

        // Extract ShastaZkAggregationGuestInput from config
        // The caller should provide this in config["shasta_zk_aggregation_input"]
        let aggregation_input = parse_shasta_aggregation_input(config)?;
        validate_shasta_aggregation_lengths(&aggregation_input)?;

        // Prepare stdin for SP1 aggregation guest program
        // The guest reads ShastaZkAggregationGuestInput via sp1_zkvm::io::read()
        let mut stdin = SP1Stdin::new();
        stdin.write(&aggregation_input);

        // Get the proposal prover's verifying key for proof verification.
        // The proposal proofs were generated with the proposal ELF.
        let elf = Elf::from(backend.elf(ProofStage::Aggregation)?);
        let proof_mode: SP1ProofMode = effective_config.recursion.clone().into();

        match effective_config.prover.unwrap_or(ProverMode::Local) {
            ProverMode::Mock => {
                let client = ProverClient::builder().mock().build().await;
                aggregate_with_client(
                    &client,
                    elf,
                    backend,
                    &input,
                    stdin,
                    proof_mode,
                    effective_config.verify,
                )
                .await
            }
            ProverMode::Local => {
                let client = ProverClient::builder().cpu().build().await;
                aggregate_with_client(
                    &client,
                    elf,
                    backend,
                    &input,
                    stdin,
                    proof_mode,
                    effective_config.verify,
                )
                .await
            }
            ProverMode::Network => {
                let client = ProverClient::from_env().await;
                aggregate_with_client(
                    &client,
                    elf,
                    backend,
                    &input,
                    stdin,
                    proof_mode,
                    effective_config.verify,
                )
                .await
            }
        }
    }
}

async fn prove_proposal_with_client<C>(
    client: &C,
    elf: Elf,
    stdin: SP1Stdin,
    proof_mode: SP1ProofMode,
    verify: bool,
    guest_input: &GuestInput,
) -> RaikoResult<Proof>
where
    C: sp1_sdk::Prover,
{
    let pk = client.setup(elf).await.map_err(|e| {
        tracing::error!("Failed to setup SP1 proposal proving key: {:?}", e);
        RaikoError::Guest(format!("SP1 proposal setup failed: {e}"))
    })?;
    let proof = client
        .prove(&pk, stdin)
        .mode(proof_mode)
        .await
        .map_err(|e| {
            tracing::error!("Failed to generate SP1 proposal proof: {:?}", e);
            RaikoError::Guest(format!("SP1 proposal proof generation failed: {e}"))
        })?;

    if verify {
        client
            .verify(&proof, pk.verifying_key(), None)
            .map_err(|e| {
                tracing::error!("Failed to verify SP1 proposal proof: {:?}", e);
                RaikoError::Guest(format!("SP1 proposal proof verification failed: {e}"))
            })?;
    }

    let public_values = proof.public_values.as_slice();
    let input_hash = parse_shasta_proposal_input_hash(public_values);
    let proof_bytes = bincode::serialize(&proof)
        .map_err(|e| RaikoError::Guest(format!("Failed to serialize proof: {e}")))?;

    Ok(Sp1Response {
        proof: Some(alloy_primitives::hex::encode_prefixed(&proof_bytes)),
        vkey_hash: Some(pk.verifying_key().bytes32().clone()),
        input: input_hash,
        sp1_proof: Some(proof),
        vkey: Some(pk.verifying_key().clone()),
        extra_data: with_shasta_extra_data(&guest_input.proof_carry_data, "sp1", None)?,
    }
    .into())
}

async fn aggregate_with_client<C, B>(
    client: &C,
    elf: Elf,
    backend: &B,
    input: &AggregationGuestInput,
    mut stdin: SP1Stdin,
    proof_mode: SP1ProofMode,
    verify: bool,
) -> RaikoResult<Proof>
where
    C: sp1_sdk::Prover,
    B: ProverBackend,
{
    let proposal_elf = Elf::from(backend.elf(ProofStage::Proposal)?);
    let proposal_pk = client.setup(proposal_elf).await.map_err(|e| {
        tracing::error!(
            "Failed to setup SP1 proposal verifying key for aggregation: {:?}",
            e
        );
        RaikoError::Guest(format!("SP1 aggregation proposal setup failed: {e}"))
    })?;
    let verifier_key = proposal_pk.verifying_key().clone();

    for proof in &input.proofs {
        if let Some(proof_hex) = &proof.proof {
            let proof_bytes = alloy_primitives::hex::decode(proof_hex)
                .map_err(|e| RaikoError::Guest(format!("Failed to decode proof hex: {e}")))?;
            let sp1_proof_with_pv: SP1ProofWithPublicValues = bincode::deserialize(&proof_bytes)
                .map_err(|e| {
                    RaikoError::Guest(format!(
                        "Failed to deserialize SP1ProofWithPublicValues: {e}"
                    ))
                })?;
            match sp1_proof_with_pv.proof {
                SP1Proof::Compressed(reduce_proof) => {
                    stdin.write_proof(*reduce_proof, verifier_key.vk.clone());
                }
                _ => {
                    return Err(RaikoError::Guest(
                        "Aggregation requires Compressed proofs".to_string(),
                    ));
                }
            }
        }
    }

    let pk = client.setup(elf).await.map_err(|e| {
        tracing::error!("Failed to setup SP1 aggregation proving key: {:?}", e);
        RaikoError::Guest(format!("SP1 aggregation setup failed: {e}"))
    })?;
    let proof = client
        .prove(&pk, stdin)
        .mode(proof_mode)
        .await
        .map_err(|e| {
            tracing::error!("Failed to generate SP1 aggregation proof: {:?}", e);
            RaikoError::Guest(format!("SP1 aggregation proof generation failed: {e}"))
        })?;

    if verify {
        client
            .verify(&proof, pk.verifying_key(), None)
            .map_err(|e| {
                tracing::error!("Failed to verify SP1 aggregation proof: {:?}", e);
                RaikoError::Guest(format!("SP1 aggregation proof verification failed: {e}"))
            })?;
    }

    let public_values = proof.public_values.as_slice();
    let agg_input_hash = parse_shasta_aggregation_input_hash(public_values);
    let proof_bytes = bincode::serialize(&proof)
        .map_err(|e| RaikoError::Guest(format!("Failed to serialize proof: {e}")))?;

    Ok(Sp1Response {
        proof: Some(alloy_primitives::hex::encode_prefixed(&proof_bytes)),
        vkey_hash: Some(pk.verifying_key().bytes32().clone()),
        input: agg_input_hash,
        sp1_proof: Some(proof),
        vkey: Some(pk.verifying_key().clone()),
        extra_data: None,
    }
    .into())
}
