//! SP1 zkVM Prover for Raiko V2
//!
//! This module provides the SP1 prover implementation for generating
//! zero-knowledge proofs of Taiko block execution.

use alloy_primitives::B256;
use raiko2_pipeline::{PipelineSpec, ProofStage, ProverBackend, Sp1Backend};
use raiko2_primitives::{
    AggregationGuestInput, GuestInput, Proof, ProverConfig, RaikoError, RaikoResult,
    ShastaZkAggregationGuestInput,
};
use raiko2_protocol::ProofCarryData;
use serde::{Deserialize, Serialize};
use sp1_sdk::{
    HashableKey, ProverClient, SP1ProofMode, SP1ProofWithPublicValues, SP1Stdin, SP1VerifyingKey,
};
use tracing::info;

/// SP1 prover configuration parameters.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Sp1Config {
    /// Proof mode (Core, Compressed, Plonk).
    #[serde(default)]
    pub recursion: RecursionMode,
    /// Prover mode (Mock, Local, Network).
    pub prover: Option<ProverMode>,
    /// Whether to verify the proof after generation.
    #[serde(default = "default_true")]
    pub verify: bool,
}

const fn default_true() -> bool {
    true
}

impl Default for Sp1Config {
    fn default() -> Self {
        Self {
            recursion: RecursionMode::Plonk,
            prover: None,
            verify: true,
        }
    }
}

/// SP1 proof recursion mode.
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum RecursionMode {
    /// Core proof (no recursion).
    Core,
    /// Compressed proof.
    Compressed,
    /// Plonk proof (on-chain verifiable).
    #[default]
    Plonk,
}

impl From<RecursionMode> for SP1ProofMode {
    fn from(value: RecursionMode) -> Self {
        match value {
            RecursionMode::Core => SP1ProofMode::Core,
            RecursionMode::Compressed => SP1ProofMode::Compressed,
            RecursionMode::Plonk => SP1ProofMode::Plonk,
        }
    }
}

/// SP1 prover mode.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "lowercase")]
pub enum ProverMode {
    /// Mock prover for testing.
    Mock,
    /// Local CPU prover.
    Local,
    /// Network prover (Succinct network).
    Network,
}

/// SP1 proof response.
#[derive(Clone, Serialize, Deserialize)]
pub struct Sp1Response {
    /// Hex-encoded serialized proof
    pub proof: Option<String>,
    /// Verifying key hash (bytes32)
    pub vkey_hash: Option<String>,
    /// Public input commitment
    pub input: B256,
    /// For aggregation
    pub sp1_proof: Option<SP1ProofWithPublicValues>,
    /// Verifying key for verification
    #[serde(skip)]
    pub vkey: Option<SP1VerifyingKey>,
}

impl From<Sp1Response> for Proof {
    fn from(value: Sp1Response) -> Self {
        Self {
            proof: value.proof,
            quote: value
                .sp1_proof
                .as_ref()
                .map(|p| serde_json::to_string(&p.proof).unwrap()),
            input: Some(value.input),
            uuid: value.vkey_hash,
            kzg_proof: None,
            extra_data: None,
        }
    }
}

/// SP1 Prover for Shasta batch proofs.
pub struct Sp1Prover {
    config: Sp1Config,
}

impl Sp1Prover {
    /// Create a new SP1 prover with the given configuration.
    pub const fn new(config: Sp1Config) -> Self {
        Self { config }
    }
}

#[async_trait::async_trait]
impl<S> crate::Prover<S, Sp1Backend> for Sp1Prover
where
    S: PipelineSpec<Sp1Backend>,
    Sp1Backend: ProverBackend<S>,
{
    async fn prove(
        &self,
        input: GuestInput,
        config: &ProverConfig,
        spec: &S,
    ) -> RaikoResult<Proof> {
        info!("Starting SP1 batch proof generation...");

        // Extract ProofCarryData from config if available
        let proof_carry_data: ProofCarryData = serde_json::from_value(
            config
                .get("proof_carry_data")
                .cloned()
                .unwrap_or(serde_json::Value::Null),
        )
        .unwrap_or_default();

        // Prepare stdin for SP1 guest program
        // The guest reads:
        // 1. GuestInput via read_vec() + bincode deserialize
        // 2. ProofCarryData via read()
        let mut stdin = SP1Stdin::new();

        // Serialize GuestInput with bincode and write as bytes (for read_vec)
        let input_bytes = bincode::serialize(&input)
            .map_err(|e| RaikoError::Guest(format!("Failed to serialize input: {}", e)))?;
        stdin.write_slice(&input_bytes);

        // Write ProofCarryData (for sp1_zkvm::io::read())
        stdin.write(&proof_carry_data);

        // Create prover client
        let client = ProverClient::from_env();

        // Use proposal ELF (will be generated by build-guest.sh)
        let backend = Sp1Backend;
        let elf = backend.elf(spec, ProofStage::Proposal)?;

        // Setup proving key and verifying key
        let (pk, vk) = client.setup(elf);

        // Get proof mode
        let proof_mode: SP1ProofMode = self.config.recursion.clone().into();

        // Generate proof
        let proof = client
            .prove(&pk, &stdin)
            .mode(proof_mode)
            .run()
            .map_err(|e| {
                tracing::error!("Failed to generate SP1 batch proof: {:?}", e);
                RaikoError::Guest(format!("SP1 batch proof generation failed: {}", e))
            })?;

        info!("SP1 batch proof generated successfully");

        // Verify proof if configured
        if self.config.verify {
            client.verify(&proof, &vk).map_err(|e| {
                tracing::error!("Failed to verify SP1 batch proof: {:?}", e);
                RaikoError::Guest(format!("SP1 batch proof verification failed: {}", e))
            })?;
            info!("SP1 batch proof verified successfully");
        }

        // Extract public values (instance_hash + subproof_input_hash = 64 bytes)
        let public_values = proof.public_values.as_slice();
        let input_hash = if public_values.len() >= 32 {
            B256::from_slice(&public_values[..32])
        } else {
            B256::default()
        };

        // Encode proof
        let proof_bytes = bincode::serialize(&proof)
            .map_err(|e| RaikoError::Guest(format!("Failed to serialize proof: {}", e)))?;

        Ok(Sp1Response {
            proof: Some(alloy_primitives::hex::encode_prefixed(&proof_bytes)),
            vkey_hash: Some(vk.bytes32()),
            input: input_hash,
            sp1_proof: Some(proof),
            vkey: Some(vk),
        }
        .into())
    }

    async fn aggregate(
        &self,
        input: AggregationGuestInput,
        config: &ProverConfig,
        spec: &S,
    ) -> RaikoResult<Proof> {
        info!(
            "Starting SP1 aggregation proof generation with {} proofs...",
            input.proofs.len()
        );

        // Extract ShastaZkAggregationGuestInput from config
        // The caller should provide this in config["shasta_zk_aggregation_input"]
        let aggregation_input: ShastaZkAggregationGuestInput = serde_json::from_value(
            config
                .get("shasta_zk_aggregation_input")
                .cloned()
                .ok_or_else(|| {
                    RaikoError::InvalidRequestConfig(
                        "Missing 'shasta_zk_aggregation_input' in config".to_string(),
                    )
                })?,
        )
        .map_err(|e| {
            RaikoError::InvalidRequestConfig(format!("Failed to parse aggregation input: {}", e))
        })?;

        // Validate input length matches
        if aggregation_input.block_inputs.len() != aggregation_input.proof_carry_data_vec.len() {
            return Err(RaikoError::InvalidRequestConfig(
                "Mismatched block_inputs and proof_carry_data_vec lengths".to_string(),
            ));
        }

        let backend = Sp1Backend;

        // Prepare stdin for SP1 aggregation guest program
        // The guest reads ShastaZkAggregationGuestInput via sp1_zkvm::io::read()
        let mut stdin = SP1Stdin::new();
        stdin.write(&aggregation_input);

        // Get the batch prover's verifying key for proof verification
        // The batch proofs were generated with the batch ELF
        let batch_elf = backend.elf(spec, ProofStage::Proposal)?;
        let client = ProverClient::from_env();
        let (_, batch_vk) = client.setup(batch_elf);

        // Add SP1 proofs for verification within the guest
        // Each proof from input.proofs should be an SP1 proof that can be verified
        for proof in &input.proofs {
            // Extract the SP1ProofWithPublicValues from the Proof struct
            // The proof is stored as hex-encoded bincode in the 'proof' field
            if let Some(proof_hex) = &proof.proof {
                let proof_bytes = alloy_primitives::hex::decode(proof_hex)
                    .map_err(|e| RaikoError::Guest(format!("Failed to decode proof hex: {}", e)))?;

                let sp1_proof_with_pv: SP1ProofWithPublicValues =
                    bincode::deserialize(&proof_bytes).map_err(|e| {
                        RaikoError::Guest(format!(
                            "Failed to deserialize SP1ProofWithPublicValues: {}",
                            e
                        ))
                    })?;

                // Extract the SP1ReduceProof from the Compressed variant
                match sp1_proof_with_pv.proof {
                    sp1_sdk::SP1Proof::Compressed(reduce_proof) => {
                        stdin.write_proof(*reduce_proof, batch_vk.vk.clone());
                    }
                    _ => {
                        return Err(RaikoError::Guest(
                            "Aggregation requires Compressed proofs".to_string(),
                        ));
                    }
                }
            }
        }

        // Use Shasta aggregation ELF
        let elf = backend.elf(spec, ProofStage::Aggregation)?;

        // Setup proving key and verifying key for aggregation
        let (pk, vk) = client.setup(elf);

        // Get proof mode
        let proof_mode: SP1ProofMode = self.config.recursion.clone().into();

        // Generate aggregation proof
        let proof = client
            .prove(&pk, &stdin)
            .mode(proof_mode)
            .run()
            .map_err(|e| {
                tracing::error!("Failed to generate SP1 aggregation proof: {:?}", e);
                RaikoError::Guest(format!("SP1 aggregation proof generation failed: {}", e))
            })?;

        info!("SP1 aggregation proof generated successfully");

        // Verify proof if configured
        if self.config.verify {
            client.verify(&proof, &vk).map_err(|e| {
                tracing::error!("Failed to verify SP1 aggregation proof: {:?}", e);
                RaikoError::Guest(format!("SP1 aggregation proof verification failed: {}", e))
            })?;
            info!("SP1 aggregation proof verified successfully");
        }

        // Extract public values (agg_public_input_hash = 32 bytes)
        let public_values = proof.public_values.as_slice();
        let agg_input_hash = if public_values.len() >= 32 {
            B256::from_slice(&public_values[..32])
        } else {
            B256::default()
        };

        // Encode proof
        let proof_bytes = bincode::serialize(&proof)
            .map_err(|e| RaikoError::Guest(format!("Failed to serialize proof: {}", e)))?;

        Ok(Sp1Response {
            proof: Some(alloy_primitives::hex::encode_prefixed(&proof_bytes)),
            vkey_hash: Some(vk.bytes32()),
            input: agg_input_hash,
            sp1_proof: Some(proof),
            vkey: Some(vk),
        }
        .into())
    }
}
