[package]
name = "raiko2-primitives"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]

alethia-reth-chainspec.workspace = true

reth-revm.workspace = true
reth-chainspec.workspace = true
reth-primitives-traits.workspace = true
reth-ethereum-primitives.workspace = true
reth-stateless.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true

serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true

anyhow.workspace = true
thiserror.workspace = true
async-trait.workspace = true

kzg = { workspace = true, features = ["bincode"] }
kzg_traits.workspace = true

bincode.workspace = true
