[package]
name = "raiko2-queue"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
tokio = { workspace = true, features = ["sync"] }
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
base64.workspace = true
bincode.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
