[package]
name = "raiko2-pipeline"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
raiko2-primitives.workspace = true
raiko2-primitives-shasta.workspace = true
raiko2-protocol.workspace = true
raiko2-protocol-shasta.workspace = true
raiko2-guests.workspace = true
raiko2-stateless.workspace = true
raiko2-provider.workspace = true

reth-ethereum-primitives.workspace = true
alethia-reth-block.workspace = true
alethia-reth-consensus.workspace = true

alloy-consensus.workspace = true

tracing.workspace = true
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
alloy-trie.workspace = true
alloy-primitives.workspace = true
reth-stateless.workspace = true
