[package]
name = "raiko2-pipeline"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
raiko2-primitives = { workspace = true, default-features = false }
raiko2-primitives-shasta.workspace = true
raiko2-protocol.workspace = true
raiko2-protocol-shasta.workspace = true
raiko2-guests.workspace = true
raiko2-stateless.workspace = true
raiko2-provider = { path = "../provider", default-features = false }

reth-ethereum-primitives.workspace = true
alethia-reth-block.workspace = true
alethia-reth-consensus.workspace = true
alethia-reth-primitives.workspace = true

alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-sol-types.workspace = true

tracing.workspace = true
async-trait.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
alethia-reth-chainspec.workspace = true
alloy-eips.workspace = true
alloy-hardforks.workspace = true
alloy-trie.workspace = true
alloy-primitives.workspace = true
bincode.workspace = true
risc0-ethereum-trie.workspace = true

[features]
default = ["chain-spec-json"]
chain-spec-json = ["raiko2-primitives/chain-spec-json", "raiko2-provider/chain-spec-json"]
