[package]
name = "raiko2-guest-common"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
raiko2-primitives = { path = "../primitives", default-features = false }
raiko2-primitives-shasta = { path = "../primitives-shasta" }
raiko2-protocol = { path = "../protocol" }
raiko2-protocol-shasta = { path = "../protocol-shasta" }
raiko2-stateless = { path = "../stateless" }
taiko-client-protocol.workspace = true
alethia-reth-chainspec = { git = "https://github.com/taikoxyz/alethia-reth", rev = "6c4d19979ca632a169627c8463c7452c4b82214c", default-features = false }
alethia-reth-block = { git = "https://github.com/taikoxyz/alethia-reth", rev = "6c4d19979ca632a169627c8463c7452c4b82214c", default-features = false, features = [
    "prover",
    "serde",
] }
alethia-reth-consensus.workspace = true
alethia-reth-primitives = { git = "https://github.com/taikoxyz/alethia-reth", rev = "6c4d19979ca632a169627c8463c7452c4b82214c", default-features = false }
alloy-primitives = { version = "=1.5.7", default-features = false }
alloy-consensus = { version = "=2.0.4", default-features = false, features = ["serde"] }
alloy-sol-types = { version = "=1.5.7", default-features = false }
alloy-rlp = { version = "=0.3.15", default-features = false }
alloy-hardforks = "=0.4.7"
anyhow = "=1.0.102"
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "27bfddeada3953edc22759080a3659ccea62ca1f", default-features = false, features = [
    "serde",
] }

[dev-dependencies]
raiko2-primitives = { path = "../primitives", features = ["chain-spec-json"] }
alloy-signer = { version = "2.0", default-features = false }
alloy-signer-local = { version = "2.0", default-features = false }
risc0-ethereum-trie.workspace = true

[features]
default = []
bench = []
