[package]
name = "xtask-build-guest"
version = "0.1.0"
edition = "2024"
default-run = "xtask-build-guest"
license.workspace = true

[dependencies]
alloy-primitives = { workspace = true, optional = true }
anyhow = { workspace = true }
bincode = { workspace = true }
cargo_metadata = "0.19.2"
clap = { workspace = true }
raiko2-guests = { workspace = true, optional = true }
risc0-binfmt = "=3.0.4"
risc0-zkvm = { workspace = true, optional = true }
risc0-zkos-v1compat = "=2.2.2"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
sp1-sdk = { workspace = true }
toml = "0.9.8"

[features]
digests = ["dep:alloy-primitives", "dep:raiko2-guests", "dep:risc0-zkvm"]

[[bin]]
name = "guest-digests"
path = "src/bin/guest-digests.rs"
required-features = ["digests"]
