[package]
name = "raiko2-provider"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
alloy.workspace = true
alloy-chains.workspace = true
alloy-json-rpc.workspace = true
alloy-primitives.workspace = true
alloy-rpc-client.workspace = true
alloy-rpc-types-debug.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-trie.workspace = true
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
itertools.workspace = true
raiko2-primitives = { workspace = true, features = ["kzg-host"] }
raiko2-primitives-shasta.workspace = true
raiko2-protocol.workspace = true
raiko2-protocol-shasta.workspace = true
hex.workspace = true
serde_json.workspace = true
reth-chainspec.workspace = true
reth-ethereum-primitives.workspace = true
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-primitives-traits.workspace = true
reqwest.workspace = true
revm.workspace = true
risc0-ethereum-trie = { workspace = true, features = ["orphan"] }
alloy-sol-types.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tower.workspace = true

# Alethia reth for Taiko chains
alethia-reth-block.workspace = true
alethia-reth-chainspec.workspace = true
alethia-reth-primitives.workspace = true

[dev-dependencies]
clap.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
