[package]
name = "raiko2-provider"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
raiko2-primitives.workspace = true
reth-ethereum-primitives.workspace = true
reth-stateless.workspace = true
alloy-trie.workspace = true
alloy-primitives.workspace = true
alloy-rpc-client.workspace = true
alloy-rpc-types-eth.workspace = true
async-trait.workspace = true
reqwest.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
