[package]
name = "raiko2-primitives-shasta"
version.workspace = true
edition.workspace = true
license.workspace = true

description = "Taiko Shasta primitives for Raiko V2"

[lints]
workspace = true

[dependencies]
raiko2-primitives.workspace = true
raiko2-protocol.workspace = true
raiko2-protocol-shasta.workspace = true

alloy-primitives.workspace = true
alloy-sol-types.workspace = true
alloy-consensus.workspace = true

serde.workspace = true
serde_json.workspace = true

anyhow.workspace = true

[dev-dependencies]
bincode.workspace = true
