[package]
name = "raiko2-guest-common"
version = "0.1.0"
edition = "2021"

[dependencies]
raiko2-primitives = { path = "../../crates/primitives" }
raiko2-primitives-shasta = { path = "../../crates/primitives-shasta" }
raiko2-protocol-shasta = { path = "../../crates/protocol-shasta" }
raiko2-stateless = { path = "../../crates/stateless" }
alethia-reth-chainspec = { git = "https://github.com/taikoxyz/alethia-reth", branch = "main", default-features = false }
alethia-reth-block = { git = "https://github.com/taikoxyz/alethia-reth", branch = "main", default-features = false, features = [
    "serde",
] }
alloy-primitives = { version = "1.5.0", default-features = false }
alloy-consensus = { version = "1.0", default-features = false, features = ["serde"] }
alloy-sol-types = { version = "1.5.0", default-features = false }
anyhow = "1.0"
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.11.3", features = [
    "serde",
    "serde-bincode-compat",
] }

[dev-dependencies]
reth-revm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.11.3" }

[features]
default = []
bench = []

[workspace]
