[package]
name = "raiko2-guest-risc0"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

# Shasta-only binary targets for Raiko V2
[[bin]]
name = "risc0-proposal"
path = "src/proposal.rs"

[[bin]]
name = "risc0-shasta-aggregation"
path = "src/shasta_aggregation.rs"

[dependencies]
raiko2-primitives = { workspace = true }
raiko2-protocol = { workspace = true }
raiko2-stateless = { workspace = true }
reth-chainspec = { workspace = true }
reth-evm-ethereum = { workspace = true }
risc0-zkvm = { version = "3.0.4", default-features = false, features = [
    'std',
    "getrandom",
] }
alloy-primitives.workspace = true
bincode.workspace = true

[features]
default = []
